### ISSUE TITLE
Non-Recoverable error porting 0.16 save to 0.17 with this mod

### ISSUE THREAD

**Issue by ConfusedOwlet** [LuziferSenpai/Wireless-Circuit-Network#2]
Tried launching a 0.16 save on 0.17 after updating all mods (now that 0.17 is stable and officially released.) Immediately after the save loads, I get this error and the game crashes. I've tried reinstalling the mod, but no luck. A new game, however, does work, as does loading the save without the mod, saving, and loading that new save with your mod reenabled (however, all networks are deleted and must be recreated).

``` 338.293 Error MainLoop.cpp:1195: Exception at tick 22448100: The mod Wireless Circuit Network caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Wireless_Circuit_Network::on_tick (ID 0)
__Wireless_Circuit_Network__/control.lua:177: bad argument #1 of 2 to 'next' (table expected, got nil)
stack traceback:
	[C]: in function 'next'
	__Wireless_Circuit_Network__/control.lua:177: in function <__Wireless_Circuit_Network__/control.lua:174>

**Comment by LuziferSenpai** [comment]
I will fix this tomorrow, because well I forgot to implement a change from the old System to the new one! Sry!

**Comment by LuziferSenpai** [comment]
I didnt saw this earlier! sry!

**Comment by LuziferSenpai** [comment]
Well, this is not a Bug. Sry, but I intended todo that. You can read that on the Modportal ;)
