### ISSUE TITLE
Blueprintable networks

### ISSUE THREAD

**Issue by jakub-borusewicz** [LuziferSenpai/Wireless-Circuit-Network#3]
Hey, great mod!

Would be awesome if network selected in sender and receiver could be saved in blueprint, I currently use your mod a lot and having to set network manually is real pain.

**Comment by LuziferSenpai** [comment]
This is not possible with the current Modding API.
And you can copy/paste ;)

**Comment by jakub-borusewicz** [comment]
@LuziferSenpai I didn't look into the source code of this mod, but couldn't you do that similarly to how it is solved in Lua Combinator 2? It holds configuration of combinator as a separate entity - https://forums.factorio.com/viewtopic.php?t=49709
